%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass{article}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{url}
\usepackage{float}
\usepackage[utf8]{inputenc}
\usepackage[spanish]{babel}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{color}
\usepackage{hyperref}
\usepackage{subcaption}
\usepackage[margin=0.5in]{geometry}
\usepackage{soul}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
\SweaveOpts{concordance=FALSE}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{COVID-19 en Euskadi}
\date{}
\maketitle
% \tableofcontents
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lectura de datos
<<echo=FALSE, results=hide>>=
library(reshape2)
library(ggplot2)
library(xtable)
library(jsonlite)
library(RCurl)
library(tidyverse)
library(RJSONIO)
source("IrekiaCOVID19.R")
covid19jsonurl <- "https://opendata.euskadi.eus/contenidos/ds_informes_estudios/covid_19_2020/opendata/covid19.json"
dateanditems <- GetCovid19Metadata(covid19jsonurl)
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \url{http://www.euskadi.eus/boletin-de-datos-sobre-la-evolucion-del-coronavirus/web01-a2korona/es/}

% \url{https://portalcne.isciii.es/covid19/?mc_cid=d2f2d87e87&mc_eid=14d19240b8}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \section{Análisis}

<<echo=FALSE, results=hide>>=
analisislist <- GetIrekiaCovid19AnalisisData(covid19jsonurl)
analisistotaldt <- analisislist$analisistotaldt
analisisbydatedt <- analisislist$analisisbydatedt
@

\section{\Sexpr{analisislist$dataname}}

Última actualización: \Sexpr{as.Date(analisislist$lastupdate)}.

\subsection{Resumen de positivos}
\noindent \textbf{Por territorio histórico:}

<<echo=FALSE, results=hide>>=
dt <- as.data.table(dcast(analisistotaldt, TTHH~Variable, value.var="Count"))
# dt[, TotalTests:=Negativo+Positivo]
# dt[, Total:=NULL]
dt[TTHH=="Euskadi", TTHH:="TOTAL"]
dt <- dt[order(TTHH)]
# oldcols <- colnames(dt)
# newcols <- gsub("Positivo","POSITIVO",oldcols)
# newcols <- gsub("Negativo","NO POSITIVO",newcols)
# newcols <- gsub("TotalTests","TOTAL TESTS",newcols)
# setnames(dt,oldcols,newcols)
@

<<echo=FALSE, results=tex>>=
print(xtable(dt), include.rownames=FALSE,table.placement="H")
@

\newpage
\noindent \textbf{Por fecha de validación:}

<<echo=FALSE, results=hide>>=
dt <- analisisbydatedt[TTHH=="Euskadi"]
dt[, TTHH:=NULL]
dt <- as.data.table(dcast(dt, date~Variable, value.var="Count"))
# dt <- dt[, .(date,Positivo,Negativo,Total)]
dt <- dt[order(date)]
dt[, date:=as.character(as.Date(date))]
# setnames(dt,colnames(dt),c("Fecha de validación","POSITIVO","NO POSITIVO","TOTAL"))
@

<<echo=FALSE, results=tex>>=
print(xtable(dt), include.rownames=FALSE,table.placement="H",size="\\scriptsize")
@

\newpage
\noindent \textbf{Por fecha de validación y territorio histórico:}

<<echo=FALSE, results=hide>>=
dt <- analisisbydatedt[TTHH!="Euskadi"]
dt <- dt[Variable!="Total"]
dt[, NewVar:=paste(TTHH,Variable,sep=": ")]
dt[, Variable:=NULL]
dt[, TTHH:=NULL]
dt <- as.data.table(dcast(dt, date~NewVar, value.var="Count"))
dt <- dt[order(date)]
# dt[, Fecha:=as.character(as.POSIXct(date, origin="0000-01-01"))]
dt[, date:=as.character(as.Date(date))]
oldcols <- colnames(dt)
newcols <- gsub("date", "Fecha de validación", oldcols)
setnames(dt,oldcols,newcols)
@

<<echo=FALSE, results=tex>>=
print(xtable(dt), include.rownames=FALSE,table.placement="H",size="\\tiny")
@

\subsection{Casos positivos acumulados por TTHH en Euskadi}

<<echo=FALSE, results=hide>>=
gg <- PlotCasosPositivosAcumuladosPorTTHH(analisislist, plotTTHH=c("Araba", "Bizkaia", "Gipuzkoa"))
ggsave(filename="./FIGS/PositivosAcumuladosPorTTHH.pdf", plot=gg)
gg <- PlotCasosPositivosAcumuladosPorTTHH(analisislist, plotTTHH=c("Euskadi"))
ggsave(filename="./FIGS/PositivosAcumuladosEuskadi.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\begin{subfigure}{0.45\textwidth}
\includegraphics{./FIGS/PositivosAcumuladosPorTTHH.pdf}
\caption{Por TTHH en Euskadi}
\label{}
\end{subfigure}
\begin{subfigure}{0.45\textwidth}
\centering
\includegraphics{./FIGS/PositivosAcumuladosEuskadi.pdf}
\caption{Euskadi}
\label{}
\end{subfigure}
\caption{Casos positivos acumulados}
\end{figure}

\subsection{Casos positivos nuevos por TTHH en Euskadi}

<<echo=FALSE, results=hide>>=
gg <- PlotCasosPositivosNuevosPorTTHH(analisislist, plotTTHH=c("Araba", "Bizkaia", "Gipuzkoa"))
ggsave(filename="./FIGS/PositivosNuevosPorTTHH.pdf", plot=gg)
gg <- PlotCasosPositivosNuevosPorTTHH(analisislist, plotTTHH=c("Euskadi"))
ggsave(filename="./FIGS/PositivosNuevosEuskadi.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\begin{subfigure}{0.45\textwidth}
\includegraphics{./FIGS/PositivosNuevosPorTTHH.pdf}
\caption{TTHH en Euskadi}
\label{}
\end{subfigure}
\begin{subfigure}{0.45\textwidth}
\includegraphics{./FIGS/PositivosNuevosEuskadi.pdf}
\caption{Euskadi}
\label{}
\end{subfigure}
\caption{Casos positivos nuevos}
\label{}
\end{figure}

\subsection{Casos positivos nuevos por días de la semana y TTHH en Euskadi}

<<echo=FALSE, results=hide>>=
gg <- PlotCasosPositivosNuevosPorTTHHyPorDiaDeSemana(analisislist, plotTTHH=c("Araba", "Bizkaia", "Gipuzkoa"))
ggsave(filename="./FIGS/PositivosNuevosPorDiaDeLaSemanaTTHH.pdf", plot=gg)
gg <- PlotCasosPositivosNuevosPorTTHHyPorDiaDeSemana(analisislist, plotTTHH=c("Euskadi"))
ggsave(filename="./FIGS/PositivosNuevosPorDiaDeLaSemanaEuskadi.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\begin{subfigure}{0.45\textwidth}
\includegraphics{./FIGS/PositivosNuevosPorDiaDeLaSemanaTTHH.pdf}
\caption{TTHH en Euskadi}
\label{}
\end{subfigure}
\begin{subfigure}{0.45\textwidth}
\includegraphics{./FIGS/PositivosNuevosPorDiaDeLaSemanaEuskadi.pdf}
\caption{Euskadi}
\label{}
\end{subfigure}
\caption{Casos positivos nuevos por día de la semana}
\label{}
\end{figure}

% \subsection{Porcentaje de tests positivos por TTHH en Euskadi}

<<echo=FALSE, results=hide>>=
# gg <- PlotPorcentajePositivosPorTTHH(analisislist, plotTTHH=c("Araba", "Bizkaia", "Gipuzkoa"))
# ggsave(filename="./FIGS/PorcentajePositivosPorTTHH.pdf", plot=gg)
# gg <- PlotPorcentajePositivosPorTTHH(analisislist, plotTTHH=c("Euskadi"))
# ggsave(filename="./FIGS/PorcentajePositivosEuskadi.pdf", plot=gg)
@

% \begin{figure}[H]
% \centering
% \begin{subfigure}{0.45\textwidth}
% \includegraphics{./FIGS/PorcentajePositivosPorTTHH.pdf}
% \caption{TTHH en Euskadi}
% \label{}
% \end{subfigure}
% \begin{subfigure}{0.45\textwidth}
% \includegraphics{./FIGS/PorcentajePositivosEuskadi.pdf}
% \caption{Euskadi}
% \label{}
% \end{subfigure}
% \caption{Porcentaje de tests positivos}
% \label{}
% \end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
%\section{Hospitalizaciones}

<<echo=FALSE, results=hide>>=
hospitallist <- GetIrekiaCovid19HospitalizacionesData(covid19jsonurl, spanishdataname="Hospital")
hospitalbydatedt <- hospitallist$hospitalbydatedt
hospitalvars <- hospitallist$hospitalvars
@

\section{\Sexpr{hospitallist$dataname}}

<<echo=FALSE, results=hide>>=
dt <- hospitalbydatedt[date==max(date)]
dt <- dt[!grep("OSPITALERATUTAKO", hospital)]
dt <- dt[value>-1]
totaldt <- dt[, .(value=sum(value)), by=.(date, variable)]
totaldt[, hospital:="TOTAL"]
totaldt <- totaldt[,.(date,hospital,variable,value)]
dt <- as.data.table(dcast(dt, date+hospital~variable, value.var = "value"))
dt[, date:=as.character(as.Date(date))]
dt <- dt[order(hospital)]
totaldt <- as.data.table(dcast(totaldt, date+hospital~variable, value.var = "value"))
totaldt[, date:=as.character(as.Date(date))]
dt <- rbind(dt, totaldt)
oldcols <- colnames(dt)
newcols <- gsub("date","Fecha", oldcols)
for(ivar in oldcols){
  a <- hospitalvars[id==ivar]
  if(nrow(a)>0){
    newcols <- gsub(ivar,a[,value], newcols)
  }
}
setnames(dt, colnames(dt), newcols)
@

<<echo=FALSE, results=tex>>=
print(xtable(dt), include.rownames=FALSE,table.placement="H",size="\\tiny")
@

\subsection{Hospitalizaciones por hospital y por fecha}

<<echo=FALSE, results=hide>>=
gg <- PlotHospitalizacionesByDate(hospitallist)
ggsave(filename="./FIGS/Hospitalizaciones.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\includegraphics{./FIGS/Hospitalizaciones.pdf}
\caption{Número de hospitalizaciones por hospital y por fecha}
\label{}
\end{figure}

\subsection{Hospitalizaciones totales por hospital}

<<echo=FALSE, results=hide>>=
gg <- PlotHospitalizacionesTotales(hospitallist)
ggsave(filename="./FIGS/HospitalizacionesTotales.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\includegraphics{./FIGS/HospitalizacionesTotales.pdf}
\caption{Número de hospitalizaciones por hospital}
\label{}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{Letalidad}

<<echo=FALSE, results=hide>>=
# read fallecidos data
fallecidoslist <- GetIrekiaCovid19LetalidadData(covid19jsonurl, spanishdataname="letalidad")
fallecidosnotes <- fallecidoslist$letalidadnotes
fallecidosname <- fallecidoslist$dataname
fallecidoslastupdate <- fallecidoslist$lastupdate
fallecidostotalesdt <- fallecidoslist$letalidadtotaldt
fallecidosbyagedt <- fallecidoslist$letalidadbyagerangedt
# a <- strsplit(fallecidosjson, "/")
# write(getURL(fallecidosjson, encoding = "latin1"), paste("../DataIrekia/",fallecidoslastupdate,"_",a[[1]][length(a[[1]])],sep=""))
@

Nota: \Sexpr{fallecidosnotes}.
\vspace{3mm}

\noindent \textbf{Resumen de positivos:}

<<echo=FALSE, results=hide>>=
dt <- fallecidostotalesdt[date==max(date)]
posdt <- dt[grep("positive", variable)]
posdt <- posdt[, .(Fecha=as.character(as.Date(date)), Variable=variable, Positivos=value)]
posdt[grep("Men", Variable), Variable:="Hombres"]
posdt[grep("Women", Variable), Variable:="Mujeres"]
posdt[grep("Total", Variable), Variable:="Total"]
posdt[Variable!="Total", Porcentaje:=round(100*Positivos/sum(Positivos))]
posdt[Variable=="Total", Porcentaje:=round(100*Positivos/sum(Positivos))]
@

<<echo=FALSE, results=tex>>=
print(xtable(posdt), include.rownames=FALSE,table.placement="H")
@

\noindent \textbf{Positivos por franja de edad:}

<<echo=FALSE, results=hide>>=
dt <- fallecidosbyagedt[date==max(date)]
posdt <- dt[grep("positive", variable)]
posdt <- posdt[, .(Fecha=as.character(as.Date(date)), Edad=ageRange, Variable=variable, Positivos=value)]
posdt[grep("Men", Variable), Variable:="Hombres"]
posdt[grep("Women", Variable), Variable:="Mujeres"]
posdt[grep("Total", Variable), Variable:="TotalFranjaEdad"]
posdt <- as.data.table(dcast(posdt,Fecha+Edad~Variable, value.var = "Positivos"))
posdt <- rbind(posdt, posdt[,.(Edad="TOTAL", Hombres=sum(Hombres), Mujeres=sum(Mujeres), TotalFranjaEdad=sum(TotalFranjaEdad)), by=.(Fecha)])
posdt[Edad!="TOTAL", PorcentajeSobreElTotal:=round(100*TotalFranjaEdad/sum(TotalFranjaEdad), digits=1)]
posdt[Edad=="TOTAL", PorcentajeSobreElTotal:=round(100*TotalFranjaEdad/sum(TotalFranjaEdad), digits=1)]
setnames(posdt, colnames(posdt), c("Fecha","Edad","Hombres","Mujeres","Total Franja de Edad", "Porcentaje sobre el total"))
@

<<echo=FALSE, results=tex>>=
print(xtable(posdt), include.rownames=FALSE,table.placement="H")
@

\noindent \textbf{Letalidad:}

% \hl{ESTO NO COINCIDE CON EL INFORME PUBLICADO POR GV-EJ}

<<echo=FALSE, results=hide>>=
dt <- fallecidosbyagedt[date==max(date)]
dt <- dt[, .(value=sum(value)), by=.(ageRange, medida)]
total <- dt[, .(value=sum(value)), by=.(medida)]
total <- total[, ageRange:="TOTAL"]
dt <- rbind(dt, total)
dt <- as.data.table(dcast(dt, ageRange~medida, value.var = "value"))
dt <- dt[,.(ageRange,Positivos,Fallecimientos,Letalidad)]
setnames(dt, colnames(dt), c("Edad","Positivos","Fallecimientos","Letalidad"))
@

<<echo=FALSE, results=tex>>=
print(xtable(dt), include.rownames=FALSE,table.placement="H")
@

\subsection{Letalidad por franja de edad y género}

<<echo=FALSE, results=hide>>=
gg <- PlotLetalidadPorEdadYGenero(fallecidoslist)
ggsave(filename="./FIGS/LetalidadPorEdadYGenero.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\includegraphics{./FIGS/LetalidadPorEdadYGenero.pdf}
\caption{Letalidad por franja de edad y género}
\label{}
\end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
%\section{Por municipio}

<<echo=FALSE, results=hide>>=
municipiolist <- GetIrekiaCovid19MunicipioData(covid19jsonurl, spanishdataname="municipio")
municipiobydatedt <- municipiolist$municipiobydatedt
municipiovars <- municipiolist$municipiovars
@

\section{\Sexpr{municipiolist$dataname}}

Última actualización: \Sexpr{as.Date(municipiolist$lastupdate)}.

Nota: \Sexpr{municipiolist$notes}.
\vspace{3mm}

<<echo=FALSE, results=hide>>=
gg <- PlotPositivosPorMunicipio(municipiolist)
ggsave(filename="./FIGS/PositivosPorMunicipio.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\includegraphics{./FIGS/PositivosPorMunicipio.pdf}
\caption{Número de positivos por municipio}
\label{}
\end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
%\section{Por zona de salud}

<<echo=FALSE, results=hide>>=
zonadesaludlist <- GetIrekiaCovid19ZonaDeSaludData(covid19jsonurl, spanishdataname="zonas de salud")
zonadesaludbydatedt <- zonadesaludlist$zonadesaludbydatedt
zonadesaludvars <- zonadesaludlist$zonadesaludvars
@

\section{\Sexpr{zonadesaludlist$dataname}}

Última actualización: \Sexpr{as.Date(zonadesaludlist$lastupdate)}.

Nota: \Sexpr{zonadesaludlist$notes}.
\vspace{3mm}

<<echo=FALSE, results=hide>>=
gg <- PlotPositivosPorZonasDeSalud(zonadesaludlist)
ggsave(filename="./FIGS/PositivosPorZonaDeSalud.pdf", plot=gg)
@

\begin{figure}[H]
\centering
\includegraphics{./FIGS/PositivosPorZonaDeSalud.pdf}
\caption{Número de positivos por zona de salud}
\label{}
\end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
